### ISSUE TITLE
Question: what is the best strategy for using the fhir_db with isolates?

### ISSUE THREAD

**Issue by AliakseiT** [fhir-fli/fhir_db#2]
We've been experimenting with this version of fhir_db (thank you, @Dokotela!), it has a much better DB open time on startup then the previous Sembast-based one.

It does impact the UI though as it operates on the main thread. Hence, we want to try with isolates. Do you have any recommendation on how fhir_db shall be used in this case?

**Comment by Dokotela** [comment]
Generally it's been quick enough for me that I haven't really looked into it. I welcome input though if you have any ideas, suggestions, or preferences.

**Comment by AliakseiT** [comment]
> Generally it's been quick enough for me that I haven't really looked into it. I welcome input though if you have any ideas, suggestions, or preferences.

After few experiments, we've decided not to go further and use it without isolate. It looks like `hive` itself is not "isolate-ready".

The alternative with isolates already planned would be `isar`.

**Comment by Dokotela** [comment]
@AliakseiT I'm glad this worked out for you, but I'll continue to keep this in mind. I had actually wanted to use Isar (it's part of the reason I added the dbId fields to the base fhir package resources). But I ran into two issues. The first is that Isar works best using their generator, which does not work with freezed. The second is that support for maps was not great (I think it required converting maps into a json string in order to store them). But perhaps in the future I'll look into it again.

**Comment by AliakseiT** [comment]
Indeed. Maybe it would work out to keep both backend options, through next generation API.

Do you have a timeline idea when a new fhir_db can go into pub dev? Our validation strategy for SOUPs is connected to pub dev, so we are directly interested in your progress. For that matter: small [PR](https://github.com/fhir-fli/fhir_db/pull/3) fro @nikolaydymura is in.

**Comment by Dokotela** [comment]
So there's a beta version already available on pub.dev. But I think I can look through the PR and push a new version by the end of the week.
